{
	"Name": "Rocket.Unturned",
	"Version": "4.9.3.0",
	"Assemblies":
	[
		{
			"Path": "/Rocket.API.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Rocket.Core.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Rocket.Unturned.dll",
			"Role": "Both_Optional"
		}
	],
	"Dependencies":
	[
		{
			"Name": "Framework",
			"Version": "3.17.4.0"
		},
		{
			"Name": "Unturned",
			"Version": "3.17.4.0"
		}
	]
}
