{
	"IsEnabled": true,
	"Name": "Rocket.Unturned",
	"Version": "5.0.0.0",
	"Assemblies":
	[
		{
			"Path": "/System.Web.dll",
			"Role": "Server"
		},
		{
			"Path": "/System.Web.Services.dll",
			"Role": "Server"
		},
		{
			"Path": "/System.ServiceModel.dll",
			"Role": "Server"
		},
		{
			"Path": "/System.IdentityModel.dll",
			"Role": "Server"
		},
		{
			"Path": "/System.IdentityModel.Selectors.dll",
			"Role": "Server"
		},
		{
			"Path": "/System.Runtime.Serialization.dll",
			"Role": "Server"
		},
		{
			"Path": "/log4net.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.API.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Plugins.Native.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Core.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Unturned.dll",
			"Role": "Server"
		}
	],
	"Dependencies": []
} 
