{
	"Name": "Rocket.Unturned",
	"Version": "5.0.0.0",
	"Assemblies":
	[
		{
			"Path": "/Rocket.API.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Rocket.Core.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Rocket.Unturned.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.ServiceModel.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.IdentityModel.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.IdentityModel.Selectors.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.Web.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.Web.Services.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/System.Runtime.Serialization.dll",
			"Role": "Both_Optional"
		}
	],
	"Dependencies":
	[
		{
			"Name": "Framework",
			"Version": "3.17.4.0"
		},
		{
			"Name": "Unturned",
			"Version": "3.17.4.0"
		}
	]
}