{
	"Name": "Rocket.Unturned",
	"Version": "0.0.0.0",
	"Assemblies":
	[
		{
			"Path": "/Rocket.API.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Core.dll",
			"Role": "Server"
		},
		{
			"Path": "/Rocket.Unturned.dll",
			"Role": "Server"
		},
		{
			"Path": "/Microsoft.Practices.ServiceLocation.dll",
			"Role": "Server"
		},
		{
			"Path": "/Microsoft.Practices.Unity.Configuration.dll",
			"Role": "Server"
		},
		{
			"Path": "/Microsoft.Practices.Unity.ServiceLocation.dll",
			"Role": "Server"
		}
	],
	"Dependencies":
	[
		{
			"Name": "Framework",
			"Version": "3.17.4.0"
		},
		{
			"Name": "Unturned",
			"Version": "3.17.4.0"
		}
	]
}
